### PR TITLE
Refactored custom schema retrieval

### PR DESCRIPTION
**Pull request by hanna-liashchuk**
### Description
Removed DatatypeMapping.scala as it held only one data type and refactored customSchema so it's not reading redundant rows from the server

### Checklist

- [X] I have run this code in development and it appears to resolve the stated issue
- [X] This PR includes tests, or tests are not required/relevant for this PR
- [ ] I have updated the README.md file

### CODE REVIEW

**Review by VShkaberda — COMMENTED** [review]
Maybe it makes sense to handle `datetime2` and `time` types in this PR also — these types cast as string too.

**Comment by hanna-liashchuk** [comment]
@VShkaberda maybe :) datetime2 will be mapped to timestamp and what about time? spark doesn't have that kind of type, afaik

**Comment by hanna-liashchuk** [comment]
and what about tables that are already in minio with type string? schema won't match and would have to be changed manually.

**Comment by VShkaberda** [comment]
> what about tables that are already in minio with type string? schema won't match and would have to be changed manually.

Datetime saved as string should be changed to timestamp — what's wrong with this statement?

> what about time? spark doesn't have that kind of type, afaik

Yeah, as I can see there's a problem when converting `time` with hours >= 3 digits to timestamp, so that it's better to live it as string, I guess.

**Review by VShkaberda — APPROVED** [review]
Question about `datetime2` will be addressed in the separate PR.

**Comment by hanna-liashchuk** [comment]
created #65

**Pull request merged**
