### PR TITLE
Select userMetadata only from merge operations

### PR DESCRIPTION
**Pull request by hanna-liashchuk**
### Description
Select only MERGE operations from delta table history to query user metadata

### Checklist

- [X] I have run this code in development and it appears to resolve the stated issue
- [X] This PR includes tests, or tests are not required/relevant for this PR
- [ ] I have updated the README.md file

### CODE REVIEW

**Review by VShkaberda — COMMENTED** [review]
Purpose of these changes is unclear. Problem raised by this PR;
Case1:
  - after initialization there is DeltaVersion but no MERGE operation: only WRITE and SET TBLPROPERTIES (considering current library version)

Case2:
  - retention period 2 days. Sync has been stopped 3 days ago, with version, e.g. 100. Current min valid version is 150. After syncing changes manually one will never be able to proceed further if sync was made using DELETE and APPEND and/or UPDATE.

**Comment by hanna-liashchuk** [comment]
I came up with this during testing, ran OPTIMIZE on a table, and then started the CT load. In logs, I found that it cannot find the last metadata and will use minValidVersion. That's because OPTIMIZE transaction is written to the delta log without user metadata. If you think syncing from minValid is the lesser evil, I will close this pr :)

**Comment by VShkaberda** [comment]
When is it necessary to run OPTIMIZE? If it's a single time operation I don't think it's necessary to make this changes. On the other hand, OPTIMIZE could be executed with needed userMetadata, the same way it is done when running SET TBLPROPERTIES in library.

**Comment by hanna-liashchuk** [comment]
It's not necessary, it's just good practice :) 
closing this PR

**Pull request closed without merging**
